services:
  - type: web
    name: mern-chat-app
    env: node
    buildCommand: npm install && npm install --prefix frontend && npm run build --prefix frontend
    startCommand: node backend/server.js
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: RENDER_BUILDPACKS
        value: "https://github.com/heroku/heroku-buildpack-nodejs.git"
